dedupe index serialization/deserialization: create collindex object as needed, serialize when idle (#3088)
- support for kvrocks as well redis for index storage (via #3099)
- update redis/kvrocks pod to use init containers to load / save to S3
- load from s3 tarball, serialize to tarball and upload before shutting down pod
- add 'saving' state for when redis is being saved, and 'idle' for when
redis pod is shutdown
- deps: update to metacontroller 4.12.5
- depends on #3087

---------

Co-authored-by: Tessa Walsh <tessa@bitarchivist.net>

diff --git a/chart/app-templates/redis.yaml b/chart/app-templates/redis.yaml
--- a/chart/app-templates/redis.yaml
+++ b/chart/app-templates/redis.yaml
@@ -48,14 +48,13 @@ spec:
     runAsGroup: 999
     fsGroup: 999
 
-  terminationGracePeriodSeconds: 10
+  terminationGracePeriodSeconds: 300
+  restartPolicy: {{ "OnFailure" if save_dump else "Always" }}
+
   volumes:
     - name: shared-redis-conf
       configMap:
         name: shared-redis-conf
-        items:
-          - key: redis.conf
-            path: redis.conf
 
     - name: redis-data
       {% if not no_pvc %}
@@ -104,7 +103,12 @@ spec:
       image: {{ redis_image }}
       imagePullPolicy: {{ redis_image_pull_policy }}
 
-      args: ["/redis-conf/redis.conf", "--appendonly", "yes"]
+      {% if use_kvrocks %}
+      args: ["-c", "/redis-conf/kvrocks.conf", "--dir", "/data", "--appendonly", "{{ 'no' if load_dump else 'yes' }}"]
+      {% else %}
+      args: ["/redis-conf/redis.conf", "--appendonly", "{{ 'no' if load_dump else 'yes' }}"]
+      {% endif %}
+
       volumeMounts:
         - name: redis-data
           mountPath: /data
@@ -137,5 +141,131 @@ spec:
             - bash
             - -c
             - "res=$(redis-cli ping); [[ $res = 'PONG' ]]"
+
+  initContainers:
+{% if save_dump %}
+    - name: save
+      image: rclone/rclone:latest
+
+      command: ["sh", "-c"]
+      args:
+        - |
+          echo "Waiting until redis is done";
+          while [ ! -f /tmp/done ]; do 
+            sleep 1;
+          done;
+
+          set -e
+
+
+        {% if use_kvrocks %}
+          if [ ! -d /data/{{ local_file_src }} ]; then
+            echo "directory /data/{{ local_file_src }} doesn't exist, erroring"
+            exit 1
+          fi
+
+          cd /data/{{ local_file_src }}
+
+          set -o pipefail
+
+          until tar cvfz - . | tee >(sha256sum > /tmp/hash.txt) | tee >(wc -c > /tmp/size.txt) | rclone --config '' rcat remote:{{ remote_file_path }} --s3-chunk-size 100M; do
+            echo "retrying upload..."
+            sleep 1;
+          done
+
+        {% else %}
+          if [ ! -f /data/{{ local_file_src }} ]; then
+            echo "/data/{{ local_file_src }} doesn't exist!"
+            exit 1
+          fi
+
+          until rclone -vv copyto --checksum /data/{{ local_file_src }} remote:{{ remote_file_path }} --s3-chunk-size 100M; do
+            echo "retrying upload..."
+            sleep 1;
+          done
+
+        {% endif %}
+
+          size=$(cat /tmp/size.txt)
+          hash=$(awk '{ print $1 }' /tmp/hash.txt)
+
+          echo ""
+          echo "STATS: (size,hash): $size,$hash"
+
+          rm /tmp/done
+
+      restartPolicy: Always
+      lifecycle:
+        preStop:
+          exec:
+            command: ["touch", "/tmp/done"]
+
+      volumeMounts: &rclone_volumes
+        - name: redis-data
+          mountPath: /data
+
+      env: &rclone_env
+      - name: RCLONE_CONFIG_REMOTE_TYPE
+        value: "s3"
+
+      - name: RCLONE_CONFIG_REMOTE_ACCESS_KEY_ID
+        valueFrom:
+          secretKeyRef:
+            name: "{{ storage_secret_name }}"
+            key: STORE_ACCESS_KEY
+
+      - name: RCLONE_CONFIG_REMOTE_SECRET_ACCESS_KEY
+        valueFrom:
+          secretKeyRef:
+            name: "{{ storage_secret_name }}"
+            key: STORE_SECRET_KEY
+
+      - name: RCLONE_CONFIG_REMOTE_REGION
+        valueFrom:
+          secretKeyRef:
+            name: "{{ storage_secret_name }}"
+            key: STORE_REGION
+
+      - name: RCLONE_CONFIG_REMOTE_PROVIDER
+        valueFrom:
+          secretKeyRef:
+            name: "{{ storage_secret_name }}"
+            key: STORE_S3_PROVIDER
+
+      - name: RCLONE_CONFIG_REMOTE_ENDPOINT
+        value: "{{ storage_endpoint }}"
+
+      resources: &rclone_resources
+        limits:
+          memory: "200Mi"
+
+        requests:
+          memory: "200Mi"
+          cpu: "50m"
+
+{% if load_dump %}
+    - name: load
+      image: rclone/rclone:latest
+
+      command: ["sh", "-c"]
+      args:
+        - |
+          set -e
+
+        {% if use_kvrocks %}
+          mkdir -p /data/{{ local_file_dest }}
+          cd /data/{{ local_file_dest }}
+
+          rclone --config "" cat remote:{{ remote_file_path }} | tar xzf -
+
+        {% else %}
+          rclone --config "" copyto remote:{{ remote_file_path }} /data/{{ local_file_dest }}
+
+        {% endif %}
+      volumeMounts: *rclone_volumes
+      env: *rclone_env
+      resources: *rclone_resources
+{% endif %}
+{% endif %}
 
 {% endif %}
