fix check script

diff --git a/.github/workflows/frontend-build-check.yaml b/.github/workflows/frontend-build-check.yaml
--- a/.github/workflows/frontend-build-check.yaml
+++ b/.github/workflows/frontend-build-check.yaml
@@ -44,7 +44,7 @@ jobs:
         run: yarn test
       - name: Check extracted strings
         working-directory: frontend
-        run: yarn localize:extract && git diff-index --quiet HEAD -- || echo "Error extracting strings, please run \`yarn localize:extract\` from the \`frontend\` directory and commit the results." && false
+        run: yarn localize:extract && if ! git diff-index --quiet HEAD -- ; then; echo "Error extracting strings, please run \`yarn localize:extract\` from the \`frontend\` directory and commit the results."; false; fi
       - name: Localization build
         working-directory: frontend
         run: yarn localize:build
